### ISSUE TITLE
Update the iOS forms to use the new CupertinoFormSection widget

### ISSUE THREAD

**Issue by navaronbracke** [navaronbracke/weforza#152]
The current iOS forms feel rather dull (and old) in terms of styling.

There is a relatively new set of widgets in the Cupertino library that could help polish the styling of these forms.
Specifically `CupertinoFormSection` and `CupertinoFormRow`.

The affected forms are:
- [x] Settings page #196 
- [x] Member form page #276 
- [ ] Device form page
- [x] Import members page #213 
- [x] Export members page #262 
- [x] Export ride page #263 
- [x] Export rides page #263 
- [ ] Remove the custom Cupertino text field with validation message

The device form is going to need a similar redesign for the device type picker

See the excellent example in https://api.flutter.dev/flutter/cupertino/CupertinoFormRow-class.html
