### ISSUE TITLE
Use Material 3 for Android

### ISSUE THREAD

**Issue by navaronbracke** [navaronbracke/weforza#170]
Opt into Material 3 for the Android app once Flutter supports all the required components.

- [ ] Fix the AppBar theme
- [ ] Fix the scan stepper theme on Android, as the M3 AppBar changes in style
- [x] use `NavigationBar` Material 3 widget in the Android app #253 
- [x] update the elevated button theme to become filled buttons, and remove the existing elevated button theme / elevated button theme for manual selection bottom bar (the ElevatedButtonTheme in the ManualSelectionBottomBar is the one that we should be using throughout the app) #320 
- [x] update the `DestructiveButtons` theme extension to match the elevated button theme, but with a different background color (perhaps we can replace it by delegating to the existing ElevatedButton style in the theme?)  
- [x] update text button theme to M3 #321 
- [x] remove any uses of `TextButton.styleFrom()` that fall out of the regular theme usage #321
- [x] update the ride details page to use an M3 bottom app bar for the counters #253 
- [x] update the manual selection bottom bar to use an M3 bottom app bar #253 
- [x] the manual selection bottom bar should be responsive (2 rows if too small) #253 
- [x] deprecate the ManualSelectionBottomAppBarTheme #253 
- [x] the manual selection bottom bar should use a CupertinoButton instead of a filled one #253 
- [x] Fix the background color of the bottom navigation bar (its not light blue) #319 
- [x] update the background color of selected scan results to match the primary color #322 
- [x] disable overscroll effect for the manual selection list #322 
- [x] import button should be an elevated button / Cupertino filled button with a leading file icon #321
- [x] remove any uses of `ElevatedButton.styleFrom()` that fall out of the regular theme usage #320
- [x] remove any usages of `useMaterial3: true` that were used to opt-in gradually #320
- [x] remove any loose `Theme()` usages #320
- [ ] add `useMaterial3: true` to the top-level ThemeData
