### ISSUE TITLE
Fix uncaught errors from synchronously thrown errors before `catchError()` handle is installed

### ISSUE THREAD

**Issue by navaronbracke** [navaronbracke/weforza#252]
Some errors that are thrown from Futures end up being uncaught in the UI.
The current 'fix' for those bugs does not really solve the problem.

The real fix would be to migrate to using `AsyncValue`, which can synchronously handle all errors.

### TODO

- [x] remove the `ArtificialDelay` mixin #263 
- [ ] fix uncaught errors in add ride page
- [x] fix uncaught errors in device form #254 
- [x] fix uncaught errors in export ride(s) page #263
- [x] fix uncaught errors in export members page #262
- [x] fix uncaught errors in import members page #262
- [x] fix uncaught errors in member form #254
- [x] the default filename for export riders should not be empty #262
- [x] the default filename for export rides should not be empty #263
- [x] let the settings page just use a Future.delayed(), but add a TODO that explains that that line should be removed (see #202 ) #263
