### ISSUE TITLE
Transition from idle to busy in form submit button is off a little

### ISSUE THREAD

**Issue by navaronbracke** [navaronbracke/weforza#260]
The transition from the idle state to the busy state in forms sometimes makes the form shrink in size.
This has to do with the ElevatedButton / CupertinoButton size being different from the CircularProgressIndicator / CupertinoActivityIndicator.

This can be fixed by having the CircularProgressIndicator / CupertinoActivityIndicator be the same height as the button.

TODO:
- [x] Implement a form submit button that transitions to the loading state but preserves the height #276 (See `FixedHeightSubmitButton`)
- [x] Fix usage in Rider form #278 
- [x] Fix usage in Device form #278 
- [x] Fix usage in Export form #276 
- [ ] Fix usage in Add Rides form

The Import Riders form uses a centered loading indicator so it is not affected by this issue.
