### ISSUE TITLE
Bump min iOS version to iOS 13.1

### ISSUE THREAD

**Issue by navaronbracke** [navaronbracke/weforza#350]
There is a minor inconvenience with Bluetooth permissions on iOS 13.0, which is resolved in iOS 13.1
We should bump the minimum iOS version from 12.0 to 13.1.

## TODO:
- [ ] bump minimum iOS version to 13.1
- [ ] fix checkBluetoothPermission() method which now only needs the `iOS 13.1+` check
- [ ] let start & stop scan check the permission using the static attribute and remove the related comments about not checking it
